#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(){
    int random_number;
    int lives = 7;
    int attempts = 0;
    char again;
    int guess;
    

    srand(time(0));
    random_number = (rand() % 100) + 1; // number will be generated here

    printf("**************************************************");
    printf("\n      Welcome To Number Guessing Game\n");
    printf("**************************************************");
    printf("\n");

    printf("\n Instruction :");
    printf("\n----------------");
    printf("\nThe Number Will Be Automatically Generated By The Code\nJust Answer Wisely");
    
    printf("\n");
    printf("\n");
    printf("\nYour TOTAL Life :%d", lives);
    do{
        
        printf("\nGuess :");
        if(scanf("%d", &guess) != 1){
            printf("\nInvalid Input\n");
            break;
        }
        if(guess == random_number){
            printf("\n🎉 YOU WON in %d lives!\n", lives);
            printf("Attempts you have done = %d\n", attempts);
        } else{
            if(guess < random_number){
                printf("\nYour Guess LOWER Than The Actual Number...\n");
                lives--;
                attempts++;
                printf("\nLives left :%d", lives);
            } else{
                printf("\nYour Guess HIGHER Than The Actual Number...\n");
                lives--;
                attempts++;
                printf("\nLives left:%d", lives);
            }
            if(lives == 0){
                printf("\nYou LOSS >_<");
                printf("\nAcutal NUMBER was %d\n", random_number);
            }
        }
        if(lives == 0 || guess == random_number){
            random_number = (rand() % 100) + 1;
            lives = 7;
            attempts = 0;
            printf("\nDo You Wanna Play Again?? (y/ n) =\t");
            scanf(" %c", &again);
            if(again == 'n'){
                printf("\n**************************");
                printf("\n   Thank you for playing");
                printf("\n**************************");
                break;
            }
        } 
        
    } while(again == 'y'  || lives != 0);

    return 0;
}