import turtle
house = turtle.Turtle()

house.getscreen().bgcolor("lightcyan")
house.penup()
house.goto(0, 100)
house.pendown()
house.speed(19)

house.fillcolor("brown")
house.color("brown")
house.begin_fill()
house.forward(410)
house.backward(830)

house.right(-45)
house.forward(350)
house.right(90)
house.forward(350)
house.right(-90)
house.forward(350)
house.right(90)
house.forward(350)
house.end_fill()

house.penup()
house.goto(90, 230)
house.pendown()

house.fillcolor("Yellow")
house.color("Yellow")
house.begin_fill()
house.circle(50)
house.forward(20)
house.end_fill()

house.penup()
house.goto(-200, -350)
house.pendown()

house.color("black")
house.fillcolor("cyan")
house.begin_fill()
house.left(45)
house.forward(500)
house.left(90)
house.forward(250)
house.left(90)
house.forward(500)
house.left(90)
house.forward(250)
house.end_fill()

house.penup()
house.goto(-200, -100)
house.pendown()

house.fillcolor("gray")
house.begin_fill()
house.left(-45)
house.backward(150)
house.left(-90)
house.backward(150)
house.end_fill()

house.color("black")
house.fillcolor("lightgreen")
house.begin_fill()
house.left(45)
house.backward(300)
house.left(-90)
house.forward(105)
house.left(90)
house.forward(410)
house.end_fill()

house.penup()
house.goto(-100, -350)
house.pendown()

house.color("black")
house.fillcolor("silver")
house.begin_fill()
house.left(-90)
house.forward(170)
house.left(90)
house.forward(100)
house.left(90)
house.forward(170)
house.left(90)
house.end_fill()

house.penup()
house.goto(50, -240)
house.pendown()

house.color("white")
house.fillcolor("deepskyblue2")
house.begin_fill()
house.left(90)
house.forward(100)
house.left(-90)
house.forward(90)
house.left(-90)
house.forward(100)
house.left(-90)
house.forward(90)
house.end_fill()

house.penup()
house.goto(160, -240)
house.pendown()

house.color("silver")
house.fillcolor("deepskyblue2")
house.begin_fill()
house.left(-90)
house.forward(100)
house.left(-90)
house.forward(90)
house.left(-90)
house.forward(100)
house.left(-90)
house.forward(90)
house.end_fill()

house.penup()
house.goto(-110, -270)
house.pendown()

house.color("brown")
house.fillcolor("brown")
house.begin_fill()
house.circle(5)
house.forward(10)
house.end_fill()

house.penup()
house.goto(-95, -50)
house.pendown()

house.color("white")
house.fillcolor("white")
house.begin_fill()
house.circle(15)
house.forward(20)
house.end_fill()

house.penup()
house.goto(312, -10)
house.pendown()

house.color("black")
house.forward(394)

house.penup()
house.goto(312, -30)
house.pendown()

house.color("black")
house.forward(373)

house.penup()
house.goto(312, -50)
house.pendown()

house.color("black")
house.forward(353)

house.penup()
house.goto(312, -70)
house.pendown()

house.color("black")
house.forward(333)

house.penup()
house.goto(312, -90)
house.pendown()

house.color("black")
house.forward(311)

house.penup()
house.goto(-100, -350)
house.pendown()

house.color("coral")
house.fillcolor("coral")
house.begin_fill()
house.left(45)
house.forward(100)

house.penup()
house.backward(100)
house.left(-45)
house.forward(100)
house.pendown()

house.color("coral")
house.left(40)
house.forward(140)
house.right(90)
house.forward(-250)
house.end_fill()


turtle.done()